apiVersion: batch/v1beta1
kind: CronJob
metadata:
  creationTimestamp: null
  name: scheduler
spec:
  jobTemplate:
    metadata:
      creationTimestamp: null
      name: scheduler
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - image: eu.gcr.io/letsboot/kubernetes-course/scheduler:latest
            name: scheduler
            env: 
            - name: SCHEDULE_URL
              value: "http://backend:8080/schedule"
            resources: {}
          restartPolicy: OnFailure
  schedule: '* * * * *'
status: {}
