apiVersion: batch/v1beta1
kind: CronJob
metadata:
  creationTimestamp: null
  name: scheduler
spec:
  jobTemplate:
    metadata:
      creationTimestamp: null
      name: scheduler
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - image: eu.gcr.io/letsboot/kubernetes-course/scheduler:latest
            name: scheduler
            resources: {}
            env: # add
            - name: SCHEDULE_URL
              value: "http://backend/schedule"
          restartPolicy: OnFailure
  schedule: '* * * * *'
status: {}
