host = "0.0.0.0"
port = 8080

[db]
host = "localhost"
port = 3306
username = "root"
password = "test"
database = "letsboot"

[queue]
host = "localhost"
port = 5672
username = "guest"
password = "guest"