apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld
spec:
  replicas: 20
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
        some-label: write-anything
    spec:
      containers:
      - name: helloworld
        image: nginx
---
apiVersion: v1
kind: Service
metadata:
  name: helloworld
spec:
  selector:
    app: helloworld
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80