apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-http-deployment
spec:
  replicas: 2 # increase to 100 as exercise
  selector:
    matchLabels:
      app: hello-http
  template:
    metadata:
      labels:
        app: hello-http
        whatever: you-want-to-label
    spec:
      containers:
      - name: hello-http
        image: strm/helloworld-http # try to switch image to nginxdemos/hello (like an udpate)