apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: database
  name: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: database
    spec:
      volumes:
      - name: database-storage
        persistentVolumeClaim:
          claimName: database-storage
      containers:
      - image: postgres
        name: postgres
        volumeMounts: 
          - mountPath: /var/lib/postgresql
            name: database-storage
        env:
          - name: POSTGRES_USER
            value: letsboot
          - name: POSTGRES_DB
            value: letsboot
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: database-postgresql
                key: postgresql-password