apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: queue
  name: queue
spec:
  ports:
  - name: 5672-5672
    port: 5672
    protocol: TCP
    targetPort: 5672
  selector:
    app: queue
  type: ClusterIP
status:
  loadBalancer: {}
