apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: queue
spec:
  selector:
    matchLabels:
      app: queue
  serviceName: "queue"
  replicas: 3
  template:
    metadata:
      labels:
        app: queue
    spec:
      terminationGracePeriodSeconds: 10
      containers: []
