apiVersion: apps/v1
kind: Deployment
metadata:
  name: crawler
  labels:
    app: crawler
spec:
  replicas: 3
  selector:
    matchLabels:
      app: crawler
  template:
    metadata:
      labels:
        app: crawler
    spec:
      containers:
        - name: crawler
          image: eu.gcr.io/letsboot/kubernetes-course/crawler:latest
          ports:
            - containerPort: 80
          env:
            - name: LETSBOOT_BACKEND.URL
              value: "backend"
            - name: LETSBOOT_QUEUE.HOST
              value: letsboot-queue-rabbitmq
            - name: LETSBOOT_QUEUE.USERNAME
              value: user
            - name: LETSBOOT_QUEUE.PASSWORD
              valueFrom:
                secretKeyRef:
                  key: data.rabbitmq-password
                  name: letsboot-queue
          volumeMounts:
            - name: rabbitmq-config-volume
              mountPath: /var/k8s/rabbitmq/config
      volumes:
        - name: rabbitmq-config-volume
          configMap:
            name: rabbitmq-service-config