# to support local docker in docker gitlab-runner 
variables:
  DOCKER_TLS_CERTDIR: ""
  DOCKER_HOST: tcp://docker:2375/

# add your ci/cd code here:

# surge_demo:
#  image: node:12
#  script:
#    - cd project-start/web
#    - yarn install
#    - yarn add surge
#    - node_modules/.bin/ng build --prod
#    - node_modules/.bin/surge -p dist/crawler/ --domain $CI_PROJECT_NAME-k8s-training.surge.sh

stages:
- test
- build
- deploy

test_go:
  stage: test
  image: golang
  script:
    - cd project-start
    - export GO111MODULE=on
    - go mod download
    - go test ./...

test_frontend:
  stage: test
  image: trion/ng-cli-karma
  script:
    - cd project-start/web
    - yarn install
    - ng test --progress false --watch false

build_backend:
  variables:
    APP: backend
  stage: build
  tags: [ docker ]
  image: docker:stable
  services:
  - docker:dind
  before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
  - docker build -t $CI_REGISTRY_IMAGE/$APP:$CI_COMMIT_SHORT_SHA -f project-start/build/package/$APP.Dockerfile project-start/
  - docker tag $CI_REGISTRY_IMAGE/$APP:$CI_COMMIT_SHORT_SHA $CI_REGISTRY_IMAGE/$APP:latest
  - docker push $CI_REGISTRY_IMAGE/$APP:$CI_COMMIT_SHORT_SHA
  - docker push $CI_REGISTRY_IMAGE/$APP:latest

build_frontend:
  variables:
    APP: frontend
  stage: build
  tags: [ docker ]
  image: docker:stable
  services:
  - docker:dind
  before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
  - docker build -t $CI_REGISTRY_IMAGE/$APP:$CI_COMMIT_SHORT_SHA -f project-start/build/package/$APP.Dockerfile project-start/
  - docker tag $CI_REGISTRY_IMAGE/$APP:$CI_COMMIT_SHORT_SHA $CI_REGISTRY_IMAGE/$APP:latest
  - docker push $CI_REGISTRY_IMAGE/$APP:$CI_COMMIT_SHORT_SHA
  - docker push $CI_REGISTRY_IMAGE/$APP:latest

build_crawler:
  variables:
    APP: crawler
  stage: build
  tags: [ docker ]
  image: docker:stable
  services:
  - docker:dind
  before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
  - docker build -t $CI_REGISTRY_IMAGE/$APP:$CI_COMMIT_SHORT_SHA -f project-start/build/package/$APP.Dockerfile project-start/
  - docker tag $CI_REGISTRY_IMAGE/$APP:$CI_COMMIT_SHORT_SHA $CI_REGISTRY_IMAGE/$APP:latest
  - docker push $CI_REGISTRY_IMAGE/$APP:$CI_COMMIT_SHORT_SHA
  - docker push $CI_REGISTRY_IMAGE/$APP:latest

build_scheduler:
  variables:
    APP: scheduler
  stage: build
  tags: [ docker ]
  image: docker:stable
  services:
  - docker:dind
  before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
  - docker build -t $CI_REGISTRY_IMAGE/$APP:$CI_COMMIT_SHORT_SHA -f project-start/build/package/$APP.Dockerfile project-start/
  - docker tag $CI_REGISTRY_IMAGE/$APP:$CI_COMMIT_SHORT_SHA $CI_REGISTRY_IMAGE/$APP:latest
  - docker push $CI_REGISTRY_IMAGE/$APP:$CI_COMMIT_SHORT_SHA
  - docker push $CI_REGISTRY_IMAGE/$APP:latest

deploy_stage:
  variables:
    CLUSTER_NAME: CHANGE-TO-YOUR-CLUSTER
  stage: deploy
  tags: [ docker ]
  image: google/cloud-sdk:alpine
  before_script:
    - echo $GCR_KEY > ${HOME}/gcloud-service-key.json
    - gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
    - gcloud components install kubectl
    - gcloud container clusters get-credentials $CLUSTER_NAME --region europe-west6 --project letsboot
  script:
    - sed -i.bak "s/(frontend|backend|scheduler|crawler):latest/$CI_COMMIT_SHORT_SHA/" project-start/deployments/*/*.yaml
    - kubectl apply -f project-start/deployments --recursive --namespace stage # add namespace
#   - kubectl apply -f project-start/gcp-ingress.yaml # removed for stage

deploy_prod:
  variables:
    CLUSTER_NAME: CHANGE-TO-YOUR-CLUSTER
  stage: deploy
  only:
    refs:
      - tags
  tags: [ docker ]
  image: google/cloud-sdk:alpine
  before_script:
    - echo $GCR_KEY > ${HOME}/gcloud-service-key.json
    - gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
    - gcloud components install kubectl
    - gcloud container clusters get-credentials $CLUSTER_NAME --region europe-west6 --project letsboot
  script:
    - sed -i.bak "s/(frontend|backend|scheduler|crawler):latest/$CI_COMMIT_SHORT_SHA/" project-start/deployments/*/*.yaml
    - kubectl apply -f project-start/deployments --recursive --namespace production 
    - kubectl apply -f project-start/gcp-ingress.yaml