host = "0.0.0.0"
port = 8080

[db]
host = "localhost"
port = 5432
username = "letsboot"
password = "xxx" # default example - use environment variables / kubernetes secrets
database = "letsboot" 

[queue]
host = "localhost"
port = 5672
username = "letsboot"
password = "xxx" # default example - use environment variables / kubernetes secrets