apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: scheduler
spec:
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  schedule: "@hourly"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: scheduler
              image: eu.gcr.io/letsboot/kubernetes-course/scheduler
          restartPolicy: Never