apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: database
  name: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  serviceName: database-postgresql
  volumeClaimTemplates:
    - metadata:
        name: database
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 2Gi
  template:
    metadata:
      labels:
        app: database
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - image: postgres
          resources:
            requests:
              memory: 100M
          name: postgres
          env:
            - name: POSTGRES_USER
              value: letsboot
            - name: POSTGRES_DB
              value: letsboot
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-postgresql
                  key: postgresql-password
          volumeMounts:
            - mountPath: /var/lib/postgresql
              name: database
          ports:
            - containerPort: 5432
