apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: crawler
  name: crawler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crawler
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: crawler
    spec:
      containers:
      - image: eu.gcr.io/letsboot/kubernetes-course/crawler:latest
        name: crawler
        volumeMounts:
          - mountPath: /var/data
            name: page-storage
        env:
          - name: LETSBOOT_BACKEND.URL
            value: http://backend
          - name: LETSBOOT_QUEUE.HOST
            value: queue
          - name: LETSBOOT_QUEUE.USERNAME
            value: user
          - name: LETSBOOT_QUEUE.PASSWORD
            valueFrom:
              secretKeyRef:
                name: queue-rabbitmq
                key: rabbitmq-password        
      volumes: #add
      - name: page-storage
        persistentVolumeClaim:
          claimName: page-storage
