apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: queue
spec:
  serviceName: queue-rabbitmq
  selector:
    matchLabels:
      app: queue
  template:
    metadata:
      labels:
        app: queue
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: queue
          image: rabbitmq:3
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: user
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  key: rabbitmq-password
                  name: queue-rabbitmq
          ports:
            - containerPort: 5672
