apiVersion: v1
kind: Pod
metadata:
  labels:
    run: frontend
  name: frontend
spec:
  containers:
  - image: eu.gcr.io/letsboot/kubernetes-course/frontend
    name: frontend
    ports:
      - containerPort: 80