apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: backend
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  strategy: {}
  template:
    metadata:
      labels:
        app: backend
    spec:
      volumes: #add
      - name: page-storage
        persistentVolumeClaim:
          claimName: page-storage
      containers:
      - image: eu.gcr.io/letsboot/kubernetes-course/backend:latest
        name: backend
        volumeMounts: # add
          - mountPath: /var/data
            name: page-storage
        env:
          - name: LETSBOOT_QUEUE.HOST
            value: queue
          - name: LETSBOOT_QUEUE.USERNAME
            value: user
          - name: LETSBOOT_DB.HOST
            value: database
          - name: LETSBOOT_DB.DATABASE
            value: letsboot
          - name: LETSBOOT_DB.USERNAME
            value: letsboot
          - name: LETSBOOT_DB.TYPE
            value: postgres
          - name: LETSBOOT_QUEUE.PASSWORD
            valueFrom:
              secretKeyRef:
                name: queue-rabbitmq
                key: rabbitmq-password
          - name: LETSBOOT_DB.PASSWORD
            valueFrom:
              secretKeyRef:
                name: database-postgresql
                key: postgresql-password
