apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: backend
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: backend
    spec:
      containers:
      - image: eu.gcr.io/letsboot/kubernetes-course/backend:latest
        name: backend
        env:
          - name: LETSBOOT_QUEUE.HOST
            value: queue
          - name: LETSBOOT_QUEUE.USERNAME
            value: user
          - name: LETSBOOT_DB.HOST
            value: database
          - name: LETSBOOT_DB.DATABASE
            value: letsboot
          - name: LETSBOOT_DB.USERNAME
            value: letsboot
          - name: LETSBOOT_QUEUE.PASSWORD
            valueFrom:
              secretKeyRef:
                name: queue-rabbitmq
                key: rabbitmq-password
          - name: LETSBOOT_DB.PASSWORD
            valueFrom:
              secretKeyRef:
                name: database-postgresql
                key: postgresql-password
        resources: {}
status: {}
