[backend]
url = "http://localhost:8080"

[queue]
host = "localhost"
port = 5672
username = "letsboot"
password = "xxx" # default example - use environment variables / kubernetes secrets

[crawler]
data = "/var/data"
dump = false
